name: refresh_bot
description: A new Flutter project.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bot_storage: ^1.0.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0



flutter:
