name: flutterbots

packages:
  - packages/**


sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    usePubspecOverrides: true

scripts:

  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.

  format: melos exec -- "dart format ."

  fix_hints: melos exec -- "dart fix —apply ."

  test_coverage:
     run: |
          melos exec -- "very_good test --coverage"
          melos exec genhtml -o ./coverage/report ./coverage/lcov.info
     select-package:
       dir-exists:
         - test
