name: flutter_bots

packages:
  - packages/**

scripts:

  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.

  format: melos exec -- "dart format ."

  fix_hints: melos exec -- "dart fix —apply ."


