name: dio_refresh_bot
description: Dio interceptor which make refresh token mechanism simple, flexible and reactive.
version: 1.0.0
homepage: https://github.com/flutterbots/flutterbots

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bot_storage: ^1.0.1
  dio: ^4.0.6
  meta: ^1.7.0


dev_dependencies:
  very_good_analysis: ^2.4.0
