name: dio_refresh_bot
description: Dio interceptor which makes refresh token mechanism simple, flexible and reactive.
version: 1.0.4
homepage: https://github.com/flutterbots/flutterbots

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bot_storage: ^1.0.3+1
  dio: ^4.0.6
  equatable: ^2.0.3
  meta: ^1.7.0
  rxdart: ^0.27.4


dev_dependencies:
  very_good_analysis: ^3.0.0
