name: bot_storage
description: A useful package provide an interface to handle read, write and delete operations in reactive way
version: 1.0.4
homepage: https://github.com/flutterbots/flutterbots

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  meta: ^1.7.0
  rxdart: ^0.27.4


dev_dependencies:
  very_good_analysis: ^3.0.0

