name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/fresh_dio.yaml"
      - "packages/dio_refresh_bot/lib/**"
      - "packages/dio_refresh_bot/test/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/fresh_dio.yaml"
      - "packages/dio_refresh_bot/lib/**"
      - "packages/dio_refresh_bot/test/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
       working_directory: "packages/dio_refresh_bot"
       dart_sdk: "stable"    
  upload_cov:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: uploads covreage report
         run: curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t 7c0f8a0f-886d-4425-bec4-53ece77bf450
