name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/fresh_dio.yaml"
      - "packages/dio_refresh_bot/lib/**"
      - "packages/dio_refresh_bot/test/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/fresh_dio.yaml"
      - "packages/dio_refresh_bot/lib/**"
      - "packages/dio_refresh_bot/test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
        with:
         working_directory: "packages/dio_refresh_bot"
         dart_sdk: "stable"
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
