name: Refresh Bot Test Work

on:
  push:
    branches: [ "dev" ]
    paths:
      - "**.dart"
  pull_request:
    branches: [ "dev" ]
    paths:
    - "**.dart"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: "stable"
      working_directory: "packages/dio_refresh_bot"
